config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :notes
  get '/remove/:id', to: 'notes#remove', as: 'remove'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ActiveRecord::Base
end
  

app/models/note.rb
class Note < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy remove ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def remove
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:title, :date_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Notes", notes_path, class: "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to "Quotes", quotes_path, class: "nav-link" %>
          </li>

        </ul>
      </div>
    </div>
  </nav>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p>
    <strong>Title:</strong>
    <%= note.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= note.description %>
  </p>

</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>
<%= link_to "New note", new_note_path %>
<div id="notes">
  <% @notes.each do |note| %>
    <%= render note %>
    <p>
      <%= link_to "Show this note", note %>
    </p>
  <% end %>
</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
  <%= link_to "Custom Delete", remove_path(@note) %>
</div>

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :date_time, style: "display: block" %>
    <%= form.date_field :date_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<div id="<%= dom_id quote %>">
  <p>
    <strong>Title:</strong>
    <%= quote.title %>
  </p>

  <p>
    <strong>Date time:</strong>
    <%= quote.date_time %>
  </p>

</div>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Show this quote", @quote %> |
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quotes</h1>

<div id="quotes">
  <% @quotes.each do |quote| %>
    <%= render quote %>
    <p>
      <%= link_to "Show this quote", quote %>
    </p>
  <% end %>
</div>

<%= link_to "New quote", new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote %>

<div>
  <%= link_to "Edit this quote", edit_quote_path(@quote) %> |
  <%= link_to "Back to quotes", quotes_path %>

  <%= button_to "Destroy this quote", @quote, method: :delete %>
</div>